enum utf_8 {
// Ord converts the char to UTF8 with decimal encoding   
//  KEY                                Dec            symbol   
    
    null=                             0,
    backspace=                        8,
    tab=                              9,
    shift=                            16,
    esc=                              27,
    space=                            32,
    exclamation=                      33,            // !
    quotation=                        34,            // "
    number_sign=                      35,            // #s
    dollar=                           36,            // $
    percent=                          37,            // %
    ampersand=                        38,            // &
    apostrophe=                       39,            // '
    left_parenthesis=                 40,            // (
    right_parenthesis=                41,            // )
    asterisk=                         42,            // *
    plus_sign=                        43,            // +
    comma=                            44,            // ,
    hyphen_minus=                     45,            // -
    full_stop=                        46,            // .
    solidus=                          47,            // /
    digit_zero=                       48,            // 0
    digit_one=                        49,            // 1
    digit_two=                        50,            // 2
    digit_three=                      51,            // 3
    digit_four=                       52,            // 4
    digit_five=                       53,            // 5
    digit_six=                        54,            // 6
    digit_seven=                      55,            // 7
    digit_eight=                      56,            // 8
    digit_nine=                       57,            // 9
    colon=                            58,            // :
    semicolon=                        59,            // ;
    less_than_sign=                   60,            // <
    equals_sign=                      61,            // =
    greater_than_sign=                62,            // >
    question_mark=                    63,            // ?
    commercial_at=                    64,            // @
    A=                                65,            // A
    B=                                66,            // B
    C=                                67,            // C
    D=                                68,            // D
    E=                                69,            // E
    F=                                70,            // F
    G=                                71,            // G
    H=                                72,            // H
    I=                                73,            // I
    J=                                74,            // J
    K=                                75,            // K
    L=                                76,            // L
    M=                                77,            // M
    N=                                78,            // N
    O=                                79,            // O
    P=                                80,            // P
    Q=                                81,            // Q
    R=                                82,            // R
    S=                                83,            // S
    T=                                84,            // T
    U=                                85,            // U
    V=                                86,            // V
    W=                                87,            // W
    X=                                88,            // X
    Y=                                89,            // Y
    Z=                                90,            // Z
    left_square_bracket=              91,            // [
    reverse_solidus=                  92,            // \
    right_square_bracket=             93,            // ]
    circumflex_accent=                94,            // ^
    low_line=                         95,            // _
    grave_accent=                     96,            // `
    a=                                97,            // a
    b=                                98,            // b
    c=                                99,            // c
    d=                                100,        // d
    e=                                101,        // e
    f=                                102,        // f
    g=                                103,        // g
    h=                                104,        // h
    i=                                105,        // i
    j=                                106,        // j
    k=                                107,        // k
    l=                                108,        // l
    m=                                109,        // m
    n=                                110,        // n
    o=                                111,        // o
    p=                                112,        // p
    q=                                113,        // q
    r=                                114,        // r
    s=                                115,        // s
    t=                                116,        // t
    u=                                117,        // u
    v=                                118,        // v
    w=                                119,        // w
    x=                                120,        // x
    y=                                121,        // y
    z=                                122,        // z
    left_curly_bracket=               123,        // {
    vertical_line=                    124,        // |
    right_curly_bracket=              125,        // }
    tilde=                            126,        // ~
}